[package]
name = "codebase_rs"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = {version="0.27.2", features=["auto-initialize"]}
serde_json = "1.0.145"
strum = "0.27.2"
strum_macros = "0.27.2"
